CREATE TABLE "DIM_REGION" (
	"REGION_ID" INT NOT NULL,
	"REGION_CD" VARCHAR2(100) NOT NULL,
	"REGION_NAME" VARCHAR2(100) NOT NULL,
	create_date TIMESTAMP ,
	update_date TIMESTAMP,
	constraint DIM_REGION_PK PRIMARY KEY ("REGION_ID"));


/
CREATE TABLE "DIM_RETAILER" (
	"RETAILER_ID" INT NOT NULL,
	"RETAILER_REGION_ID" INT NOT NULL,
	"RETAILER_CD" VARCHAR2(100) NOT NULL,
	"RETAILER_ADDRESS" VARCHAR2(100) NOT NULL,
	create_date TIMESTAMP ,
	update_date TIMESTAMP ,
	constraint DIM_RETAILER_PK PRIMARY KEY ("RETAILER_ID"));


/
CREATE TABLE "DIM_EMPLOYEE" (
	"EMP_ID" INT NOT NULL,
	"EMP_CD" VARCHAR2(100) NOT NULL,
	"EMP_NAME" VARCHAR2(100) NOT NULL,
	"EMP_GENDER" VARCHAR2(1) NOT NULL,
	"EMP_ADDRESS" VARCHAR2(100) NOT NULL,
	"EMP_DOB" DATE NOT NULL,
	create_date TIMESTAMP ,
	update_date TIMESTAMP ,
	constraint DIM_EMPLOYEE_PK PRIMARY KEY ("EMP_ID"));


/
CREATE TABLE "DIM_DATE" (
	"DATE_ID" INT NOT NULL,
	"DATE_CD" DATE NOT NULL,
	"MONTH_VALUE" INT NOT NULL,
	"YEAR_VALUE" INT NOT NULL,
	"QUARTER_VALUE" INT NOT NULL,
	create_date TIMESTAMP ,
	update_date TIMESTAMP ,
	constraint DIM_DATE_PK PRIMARY KEY ("DATE_ID"));


/
CREATE TABLE "DIM_PRODUCT" (
	"PRODUCT_ID" INT NOT NULL,
	"PRODUCT_CD" VARCHAR2(100) NOT NULL,
	"PRODUCT_DESC" VARCHAR2(100) NOT NULL,
	"PRODUCT_COST" DECIMAL(12) NOT NULL,
	create_date TIMESTAMP ,
	update_date TIMESTAMP ,
	constraint DIM_PRODUCT_PK PRIMARY KEY ("PRODUCT_ID"));


/
CREATE TABLE "DIM_CUSTOMER" (
	"CUST_ID" INT NOT NULL,
	"CUST_NAME" VARCHAR2(100) NOT NULL,
	"CUSR_ADDRESS" VARCHAR2(100) NOT NULL,
	"CUST_MOB" VARCHAR2(100) NOT NULL,
	"CUST_EMAIL" VARCHAR2(100) NOT NULL,
	create_date TIMESTAMP ,
	update_date TIMESTAMP ,
	constraint DIM_CUSTOMER_PK PRIMARY KEY ("CUST_ID"));


/
CREATE TABLE "FACT_SALES" (
	"SALES_ID" INT NOT NULL,
	"ORDER_ID" INT NOT NULL,
	"EMP_ID" INT NOT NULL,
	"RETAILER_ID" INT NOT NULL,
	"PRODUCT_ID" INT NOT NULL,
	"CUSTOMER_ID" INT NOT NULL,
	"SALES_DATE_ID" INT NOT NULL,
	"SALES_QUANTITY" INT NOT NULL,
	"SALES_VALUE" DECIMAL(12) NOT NULL,
	create_date TIMESTAMP ,
	update_date TIMESTAMP ,
	constraint FACT_SALES_PK PRIMARY KEY ("SALES_ID"));


/
CREATE TABLE "DIM_ORDER" (
	"ORDER_ID" INT NOT NULL,
	"ORDER_CD" VARCHAR2(100) NOT NULL,
	create_date TIMESTAMP ,
	update_date TIMESTAMP ,
	constraint DIM_ORDER_PK PRIMARY KEY ("ORDER_ID"));


/

ALTER TABLE "DIM_RETAILER" ADD CONSTRAINT "DIM_RETAILER_fk0" FOREIGN KEY ("RETAILER_REGION_ID") REFERENCES "DIM_REGION"("REGION_ID");





ALTER TABLE "FACT_SALES" ADD CONSTRAINT "FACT_SALES_fk0" FOREIGN KEY ("ORDER_ID") REFERENCES "DIM_ORDER"("ORDER_ID");
ALTER TABLE "FACT_SALES" ADD CONSTRAINT "FACT_SALES_fk1" FOREIGN KEY ("EMP_ID") REFERENCES "DIM_EMPLOYEE"("EMP_ID");
ALTER TABLE "FACT_SALES" ADD CONSTRAINT "FACT_SALES_fk2" FOREIGN KEY ("RETAILER_ID") REFERENCES "DIM_RETAILER"("RETAILER_ID");
ALTER TABLE "FACT_SALES" ADD CONSTRAINT "FACT_SALES_fk3" FOREIGN KEY ("PRODUCT_ID") REFERENCES "DIM_PRODUCT"("PRODUCT_ID");
ALTER TABLE "FACT_SALES" ADD CONSTRAINT "FACT_SALES_fk4" FOREIGN KEY ("CUSTOMER_ID") REFERENCES "DIM_CUSTOMER"("CUST_ID");
ALTER TABLE "FACT_SALES" ADD CONSTRAINT "FACT_SALES_fk5" FOREIGN KEY ("SALES_DATE_ID") REFERENCES "DIM_DATE"("DATE_ID");


