CREATE TABLE "SRC_RETAIL_STORE" (
	"RETAIL_CD" VARCHAR2(100) NOT NULL,
	"RETAIL_NAME" VARCHAR2(100) NOT NULL,
	"RETAIL_ADDRESS" VARCHAR2(100) NOT NULL,
	"RETAIL_REGION" VARCHAR2(100) NOT NULL,
	constraint SRC_RETAIL_STORE_PK PRIMARY KEY ("RETAIL_CD"));


/
CREATE TABLE "SRC_PRODUCT_DATA" (
	"PROD_CD" VARCHAR2(100) NOT NULL,
	"PROD_DESC" VARCHAR2(100) NOT NULL,
	"PROD_PRICE" DECIMAL NOT NULL,
	constraint SRC_PRODUCT_DATA_PK PRIMARY KEY ("PROD_CD"));


/
CREATE TABLE "SRC_CUSTOMER_DATA" (
	"CUST_NAME" VARCHAR2(100) NOT NULL,
	"CUST_MOB" VARCHAR2(100) NOT NULL,
	"CUST_EMAIL" VARCHAR2(100) NOT NULL,
	"CUST_ADDR" VARCHAR2(100) NOT NULL);


/
CREATE TABLE "SRC_EMP_DATA" (
	"EMP_CD" VARCHAR2(100) NOT NULL,
	"RETAIL_CD" VARCHAR2(100) NOT NULL,
	"EMP_NAME" VARCHAR2(100) NOT NULL,
	"EMP_GENDER" VARCHAR2(1) NOT NULL,
	"EMP_DOB" DATE NOT NULL,
	"EMP_ADDRESS" VARCHAR2(100) NOT NULL,
	constraint SRC_EMP_DATA_PK PRIMARY KEY ("EMP_CD"));


/
CREATE TABLE "SRC_SALES" (
	"ORDER_ID" VARCHAR2(100) NOT NULL,
	"ORDER_DATE" DATE NOT NULL,
	"PROD_CD" VARCHAR2(100) NOT NULL,
	"EMP_CD" VARCHAR2(100) NOT NULL,
	"RETAIL_CD" VARCHAR2(100) NOT NULL,
	"CUST_CD" VARCHAR2(100) NOT NULL,
	"QUANTITY" INT NOT NULL,
	"AMOUNT_PAID" DECIMAL(12,2) NOT NULL);


/

